// Files
export const REQUEST_CREATE_FILE = 'REQUEST_CREATE_FILE'
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS'
export const CREATE_FILE_FAIL = 'CREATE_FILE_FAIL'

export const REQUEST_DELETE_FILE = 'REQUEST_DELETE_FILE'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL'

export const REQUEST_FETCH_FILES = 'REQUEST_FETCH_FILES'
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS'
export const FETCH_FILES_FAIL = 'FETCH_FILES_FAIL'

export const REQUEST_APPEND_FILE_BLOB = 'REQUEST_APPEND_FILE_BLOB'
export const APPEND_FILE_BLOB_SUCCESS = 'APPEND_FILE_BLOB_SUCCESS'
export const APPEND_FILE_BLOB_FAIL = 'APPEND_FILE_BLOB_FAIL'
export const ADD_BLOB_SUCCESS = 'ADD_BLOB_SUCCESS'
