// Files
export const REQUEST_CREATE_FILE = 'REQUEST_CREATE_FILE'
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS'
export const CREATE_FILE_FAIL = 'CREATE_FILE_FAIL'

export const REQUEST_DELETE_FILE = 'REQUEST_DELETE_FILE'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL'

export const REQUEST_FETCH_FILES = 'REQUEST_FETCH_FILES'
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS'
export const FETCH_FILES_FAIL = 'FETCH_FILES_FAIL'
